# Generated by Django 5.2.4 on 2025-08-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyaccount',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_accounts', to='loyalty.tier'),
        ),
        migrations.AlterUniqueTogether(
            name='customertenantmembership',
            unique_together={('customer', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyaccount',
            unique_together={('membership', 'program')},
        ),
    ]
